### PR TITLE
Fix bug in issue 24 and add argument checking for issue 25

### PR DESCRIPTION
**Pull request by jeanetteclark**
Mostly I'd like to merge this in and make a minor release to fix the bug identified when you search for more than one identifier. This will be important to fix before we present

### CODE REVIEW

**Review by mbjones — CHANGES_REQUESTED** [review]
@jeanetteclark This looks great, although I didn't have time to execute it and run the tests. But I'm sure you did through CI! 

My only comment is that I think it would be better to avoid introducing the dependency on `tidyr`. In general, every dependency results in additional maintenance headaches. So I try to avoid any dependencies unless they are really fundamentally needed. Depending on dplyr and tidyr in particular introduce a lot of churn because those packages get versioned a lot, which means we have to test (and often patch) our packages whenever they change theirs. Given that we use so little of those in this package, and its just syntactic sugar over base R, I suggest we factor out tidyr. Thoughts?

**Comment by jeanetteclark** [comment]
ah yes absolutely. I meant to do that refactor because I had the same thought. Will hopefully get to it today or tomorrow

**Comment by jeanetteclark** [comment]
@mbjones updated to remove dependency.

**Review by mbjones — APPROVED** [review]
Thanks for the dependency change. Looks good to me.

**Pull request merged**
